# Generated by Django 4.1 on 2022-10-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='image',
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
