# Generated by Django 4.1 on 2022-11-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0003_place_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='visitor',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
