# Generated by Django 4.1 on 2022-10-12 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0002_project_remove_registrant_tender_id_alter_company_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrant',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tender.company'),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tender.project'),
        ),
    ]
