# Generated by Django 4.1 on 2022-10-13 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0005_rename_chosen_registrant_project_chosen_registrant_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='registrant_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='chosen_registrant_id',
        ),
        migrations.RemoveField(
            model_name='registrant',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='registrant',
            name='project_id',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Registrant',
        ),
    ]
