# Generated by Django 4.1 on 2022-10-13 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0008_rename_user_id_company_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Registrant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('offer_price', models.IntegerField()),
                ('deal_price', models.IntegerField()),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('is_chosen', models.BooleanField(default=False)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tender.company')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tender.project')),
            ],
        ),
    ]
