# Generated by Django 4.1 on 2022-10-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0009_project_registrant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='closed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
