# Generated by Django 4.1 on 2022-10-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0011_project_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
