# Generated by Django 4.1 on 2022-10-13 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0012_alter_project_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='photo',
        ),
    ]
