# Generated by Django 4.1 on 2022-10-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0013_remove_project_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='photo',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='photo',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
