# Generated by Django 4.1 on 2022-10-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0014_company_photo_project_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrant',
            name='deal_price',
            field=models.IntegerField(null=True),
        ),
    ]
