# Generated by Django 4.1 on 2022-10-26 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0018_alter_registrant_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrant',
            name='deal_price',
        ),
    ]
