# Generated by Django 4.1 on 2022-10-30 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0019_remove_registrant_deal_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
