# Generated by Django 4.1 on 2022-10-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0020_delete_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
