# Generated by Django 4.1 on 2022-10-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0021_alter_company_photo_alter_project_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
