# Generated by Django 4.1 on 2022-10-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0022_alter_project_closed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
