# Generated by Django 4.1 on 2022-11-02 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0024_image_alter_company_photo_alter_project_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='project',
            name='photo',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
