# Generated by Django 4.1 on 2022-10-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0002_remove_waste_price_waste_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='waste',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
