# Generated by Django 4.1 on 2022-10-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0003_waste_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waste',
            name='waste_type',
            field=models.CharField(choices=[('plastic', 'plastic'), ('metal', 'metal'), ('paper', 'paper'), ('glass', 'glass')], default='plastic', max_length=100),
        ),
    ]
