# Generated by Django 4.1 on 2022-11-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0004_alter_waste_waste_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waste',
            name='waste_type',
            field=models.CharField(max_length=100),
        ),
    ]
