# Generated by Django 4.1 on 2022-11-02 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='photo',
        ),
    ]
