# Generated by Django 4.1 on 2022-12-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0002_remove_items_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.TextField(),
        ),
    ]
