# Generated by Django 4.1 on 2022-10-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.BigIntegerField()),
                ('contact_name', models.TextField()),
                ('contact_number', models.TextField()),
            ],
        ),
    ]
