# Generated by Django 4.1 on 2022-11-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marine', '0005_items_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='contact_name',
            field=models.CharField(max_length=255),
        ),
    ]
