# Generated by Django 4.1 on 2022-12-12 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marine', '0008_items_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='photo',
        ),
    ]
